
server:
  port: 8080

spring:
  application:
    name: gamecircle
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
    root: TRACE

logging:
  level:
    org:
      springframework: DEBUG
  com:
    gamecircle: DEBUG